Added Unit Tests and modifications on derange function
stefanalexlupu/derange pull request #1
Opened 2020-08-10 12:01 UTC by kulcsarrudolf

Hello Stefan,

I found this project on LinkedIn and I considered that this project can be a good chance to me to practice Jest. And I hope that some unit tests can be helpful for you.
And besides that I did some modifications on **index.js:derange()** function.

P.S.: My formatting settings are different from yours. I recommend to set your settings in **package.js**. I already did some changes, but our settings are still different (see: README.MD and index.js).

2020-08-10 18:58 UTC, stefanalexlupu commented
Thank you @kulcsarrudolf for contributing! This project can really use some testing.

I will take the proper time to review these changes to make sure they are going in the direction I want this project to go.

2020-08-10 20:02 UTC, stefanalexlupu requested changes
Thank you for contributing, this PR is on the right path but some things need adjusting

* please remove code styling changes, since this PR only addresses the tests
* add the dependencies for modules used
* update documentation where necessary

2020-08-10 20:02 UTC, stefanalexlupu commented on package.json
> +  "prettier": {
If your focus here is adding tests, it would be great to just focus on that. Code style changes are so debatable and the single policy I want right now in this repo is "use standard ESLint". You can create a different PR for handling this, if you really want to, here are some recommendations:

* We can't really assume that everybody has prettier installed, we should also properly add it as dev dependency.
* Please add configuration in a dedicated file like `.prettierrc.json`
* Just to make sure that  there aren't any conflicts between ESLint configuration and Prettier we could use [something like this](https://github.com/prettier/eslint-config-prettier).

There are way too many changes related to code style so I'm just thinking that  if you want to focus on writing tests for this PR, you could just use the local ESLint config (as recommended). You said something about having differences; if you have some global config, please use the local config instead since if anybody else will get into this code it should be uniform.

2020-08-10 20:02 UTC, stefanalexlupu commented on README.md
> +element, the ouptut of the function for this cases will be the empty set.
Since you throw an exception now instead of returning the empty set, you could update this section as well.

2020-08-10 20:02 UTC, stefanalexlupu commented on src/index.js
> +  const derangedArray = displace(indices, 1)
These edits break the function. It's my bad for not documenting the algorithm. In short, here's what is happening.

Since the only restriction that is imposed is that positions should no longer be the same, I perform a position shuffle instead of shuffling the entire array. This is supposed to save a ton of memory if the array is filled with objects instead of primitives. In this section I actually generate the new array based on the indices that I shuffled to fit the derangement criteria.

Here's the output of the function with this changes (using example.js):

```
a -> 2
b -> 0
c -> 5
d -> 1
e -> 6
f -> 4
g -> 3
```
It should instead be:

```
a -> c
b -> a
c -> f
d -> b
e -> g
f -> e
g -> d
```

Your tests pass because you compare `'a'` with `2` and expect it to not be true - which will always happen, even if you compare `'a'` with `0`.

Please revert changes in lines 46 -> 52. You can keep the name `derangedArray` for `a`, it's way better. Kudos to you on that one!

2020-08-10 20:02 UTC, stefanalexlupu commented on package.json
> +    "test": "jest"
Please don't assume that everybody has jest installed globally and add it as a dev-dependency 😁

2020-08-10 20:02 UTC, stefanalexlupu commented on src/___test___/index.test.js
> +  expect(deranged[0]).not.toBe('a')
What about using something like this:

```
for (let i = 0; i < deranged.length; i++) {
    expect(deranged[i]).not.toBe(array[i])
  }
```

2020-08-10 20:02 UTC, stefanalexlupu commented on src/___test___/index.test.js
> +test('test deregement of a set with 2 elements', () => {
This is redundant since you have the first test.

2020-08-10 20:02 UTC, stefanalexlupu commented on src/___test___/index.test.js
> +test('Test when the array is empty', () => {
It would be great if the test names were a bit more descriptive. Here something like:

> Empty set should throw exception

I searched for best practices when using jest but didn't find anything conclusive. If you use a pattern, please document it in a `README.md` file in the root test directory

2020-08-10 20:02 UTC, stefanalexlupu commented on src/___test___/index.test.js
> +
Since the result is different each time because of the random factor, there should also be a statistic test, like maybe generating 100 derangements and making sure that all pass the test.

2020-08-10 20:02 UTC, stefanalexlupu commented on src/___test___/index.test.js
> +})
Why not simply use something like an `index.test.js` in the same folder as `index.js`, namely in the `src` folder?

2020-08-12 06:06 UTC, kulcsarrudolf commented
@stefanalexlupu thank you for your feedback. I will make the changes based on your suggestions. Hava a nice day!

2020-08-12 06:26 UTC, kulcsarrudolf commented on package.json
> +  "prettier": {
@stefanalexlupu do you use VS Code or something other? Could you please send me your code formatting settings?

2020-08-12 06:30 UTC, kulcsarrudolf commented on src/index.js
> +  const derangedArray = displace(indices, 1)
You're right. This means that my tests are also bad. I will improve this part.

2020-08-12 11:22 UTC, stefanalexlupu commented on package.json
> +  "prettier": {
I use VSCode, I think I should add an .editorconfig which might help, right?

2020-08-13 10:19 UTC, kulcsarrudolf commented on package.json
> +  "prettier": {
I don't have much experience with VS Code. I looked a little further, and I think that an **.editorconfig** can be usefull. It is important to define an uniform code format for this project.

2020-08-13 13:01 UTC, stefanalexlupu requested changes

2020-08-13 13:01 UTC, stefanalexlupu commented on src/index.js
> +    throw new Error('At least 2 elements are required')
I've just had a look at this kind of change. It's actually a breaking change and if we make it we should do it separately in a v2.* so I'll just create an issue for it to treat it in a next release.

You can [read more about this here](https://docs.npmjs.com/about-semantic-versioning)

I don't want to pretend like this is a huge library because it is not haha 😂 but if there's a code I think we should follow it. Especially since there's now almost 100 downloads of this package 🎉

2020-08-19 14:38 UTC, stefanalexlupu commented
@kulcsarrudolf will you continue work on this PR?

2020-08-19 15:08 UTC, kulcsarrudolf commented
> @kulcsarrudolf will you continue work on this PR?

Sorry, I was busy and forgot to work on this PR. I will update today.

2020-08-19 22:06 UTC, kulcsarrudolf commented on src/index.js
> +  const derangedArray = displace(indices, 1)
I reverted my changes.

2020-08-19 22:13 UTC, kulcsarrudolf commented on src/___test___/index.test.js
> +test('test deregement of a set with 2 elements', () => {
I think it is nice to have tests with edge-cases.

2020-08-19 22:15 UTC, kulcsarrudolf commented on src/___test___/index.test.js
> +
Good idea! :)

2020-08-19 22:21 UTC, kulcsarrudolf commented on src/___test___/index.test.js
> +})
Maybe in the future you will have more test files for **index.js**.

2020-08-19 22:26 UTC, kulcsarrudolf commented on src/index.js
> +    throw new Error('At least 2 elements are required')
Ok. I understand.

2020-08-20 06:13 UTC, kulcsarrudolf commented
@stefanalexlupu I did some modification, but I want to check it again today.

I think I found a little bug, it is ok if I create an Issue?  

Unfortunately I squashed my commits, I just realized it wasn't a good idea. 😞

2020-08-20 07:36 UTC, stefanalexlupu commented
@kulcsarrudolf yes please create the issue :)

2020-08-20 18:34 UTC, kulcsarrudolf commented
@stefanalexlupu please review my last modifications.

Some tests are skipped, because the tested cases are not implemented. But I recomand you to cosider these tests for future versions.

![image](https://user-images.githubusercontent.com/26814593/90810706-10e91b80-e32c-11ea-9010-2c38faf141fc.png)

2020-08-21 13:01 UTC, stefanalexlupu requested changes
I really appreciate your effort but it still seems like these tests can be improved.

I asked some questions so let's discuss and see if I understood everything correctly :)

2020-08-21 13:01 UTC, stefanalexlupu commented on src/__test__/index.statistic.test.js
> +  cases.forEach((element) => {
Element is such a generic name for a variable that actually contains an array... please change it to `case` or `set`.

2020-08-21 13:01 UTC, stefanalexlupu commented on src/__test__/index.statistic.test.js
> +      const setToDerange = element
Since you will never be mutating that `setToDerange` you don't really need to create this constant. Just stick with the value passed in the `forEach` callback to avoid clutter.

2020-08-21 13:01 UTC, stefanalexlupu commented on src/__test__/index.statistic.test.js
> +        expect(setToDerange).toEqual(expect.arrayContaining([derangedSet[i]]))
According to docs: https://jestjs.io/docs/en/expect#expectarraycontainingarray

With this check you could miss the case in which not all the initial elements made it to the derangedSet.

Why not do something like:

```
expect(setToDerange).toEqual(expect.arrayContaining(derangedSet))
expect(derangedSet).toEqual(expect.arrayContaining(setToDerange))
```

outside the `for` loop

This way you make sure that all elements that went into the derange method make it out (just in a different order).

![image](https://user-images.githubusercontent.com/21083175/90891685-c667ad80-e3c4-11ea-960f-b94ae43c9958.png)

2020-08-21 13:01 UTC, stefanalexlupu commented on src/__test__/index.statistic.test.js
> +
If I understand correctly, from this point onwards you are doing the following:

1. Add each element that passes the test above into the `derangedElements` array
2. Set the `notDerangedElements` to be the rest of the `derangedSet` (do you see the irony here?)
3. Check that the derangedElements is not a subset of the set containing only the current element?  When is this ever going to fail?

I'm waiting for you to explain to me what this is looking for but it seems to me that just performing the check at line 28 + the suggested test above is enough.

If that's the case in the end, we might not need

* `derangedElements`
* `notDerangedElements`
* `removeSpecificElementFromArray`
* `expect(notDerangedElements.length).toBe(EMPTY)` (or that `EMPTY` constant for that matter)

2020-08-21 13:01 UTC, stefanalexlupu commented on src/__test__/index.test.js
> +test('Test if all of the given array elements are deranged', () => {
This might be simpler to read and understand

```
expect(setToDerange).toEqual(expect.arrayContaining(derangedSet))
expect(derangedSet).toEqual(expect.arrayContaining(setToDerange))
```

2020-08-21 13:01 UTC, stefanalexlupu commented on src/__test__/index.test.js
> +  expect(() => derange(array)).toThrowError(errorMessage)
We dropped this feature for now at least..  I logged an issue ( #4 ) for this and will add the test together with that.

It's going to be a breaking change so it will probably only happen later.

2020-08-21 13:01 UTC, stefanalexlupu commented on src/__test__/utils/utils.js
> +const utils = {
The need of test utils scares the fire out of me :))

We have to make sure we need this as per above comments. I have a strong feeling we can live without these, although I really appreciate the effort!

2020-08-21 13:01 UTC, stefanalexlupu commented on src/index.js
> +  array.forEach((i) => {
Thank you for doing this 🙌🏻

2020-08-21 16:40 UTC, kulcsarrudolf commented on src/__test__/index.statistic.test.js
> +  cases.forEach((element) => {
I deleted the **index.statistic.test.js** file.

2020-08-21 16:51 UTC, kulcsarrudolf commented on src/__test__/utils/utils.js
> +const utils = {
Yes, this is very strange. I deleted it :satisfied:

![6b4upqv6at321](https://user-images.githubusercontent.com/26814593/90914675-f45de980-e3e6-11ea-941b-796629e43e2b.jpg)

2020-08-21 16:53 UTC, kulcsarrudolf commented on src/index.js
> +  array.forEach((i) => {
This is your merit. The linter did it automatically. I like it! The pre-commit task is very useful.

2020-08-21 17:03 UTC, kulcsarrudolf commented on src/__test__/index.test.js
> +  expect(() => derange(array)).toThrowError(errorMessage)
TDD :sunglasses:
I think it is better to keep it, but it's your decision.

2020-08-21 17:06 UTC, kulcsarrudolf commented
@stefanalexlupu thank you for your constructive comments and for your time! 😃🙏

2020-08-23 00:39 UTC, stefanalexlupu commented on src/__test__/index.test.js
> +  expect(() => derange(array)).toThrowError(errorMessage)
I will create a branch for v2 after this is done and will notify you to implement this if you want 😁

2020-08-23 00:50 UTC, stefanalexlupu reviewed
![image](https://user-images.githubusercontent.com/21083175/90968315-923eda80-e4f3-11ea-8ab3-1aa8c6c8eaec.png)

I tried running the test on my local machine and it seems to not work, do you know what this error is?

I only cloned your branch and run:

```
npm i
npm run test
```

2020-08-23 01:02 UTC, stefanalexlupu commented
Update: it seems to be working with jest ^25, looking to see what changed

---

Edit: I looked at [the release docs for v26](https://jestjs.io/blog/2020/05/05/jest-26) and it seems to me that they are in the process of changing how methods are loaded into context when executing jest. I'm assuming you tested using a local installation of jest? Can you see what that is?

Maybe lock the version t v25 for now to avoid these changes?

2020-11-12 19:50 UTC, stefanalexlupu approved these changes
Thank you for your contribution @kulcsarrudolf!

2020-11-12 19:50 UTC, merged